Standardize line encodings
source-academy/modules pull request #210
Opened 2023-05-09 15:42 UTC by Yongbeom-Kim

# Description

Adds a `.gitattributes` file to standardize all line encoding to CRLF for the following files (LMK if there are any other important files to standardize, or any to omit):
- *.js
- *.ts
- *.tsx
- *.md
- *.cjs
- *.json

Fixes #209 
Sequenced after #204 (oops, sorry about that)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-05-09 17:21 UTC, RichDom2185 commented
> Sequenced after #204 (oops, sorry about that)

No worries, looks like there are now merge conflicts due to the squashing.

2023-05-10 09:16 UTC, Yongbeom-Kim commented
I've fixed the conflicts

From what I can see, there is no particular reason for CRLF, other than the fact that the current eslint rules specify CRLF in particular

2023-05-16 13:40 UTC, shenyih0ng requested changes

2023-05-16 13:40 UTC, shenyih0ng commented on .gitattributes
> +*.json text eof=crlf
i think there's a typo here:

```diff
+ eol=crlf
- eof=crlf
```

2023-05-16 13:46 UTC, shenyih0ng commented
if we want to take things even further we can introduce a [`.editorconfig` file](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#bonus-create-an-editorconfig-file) to ensure new files always have the right line endings

ref (it's a great read): https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

2023-05-29 17:42 UTC, leeyi45 commented
> if we want to take things even further we can introduce a [`.editorconfig` file](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#bonus-create-an-editorconfig-file) to ensure new files always have the right line endings
> 
> ref (it's a great read): https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

Let us just go forward with adding this. I've been searching for the longest time for some way to get vscode to standardize line endings without having to commit `.vscode`. Good to see such a solution exists.

2023-05-29 19:05 UTC, RichDom2185 commented
Let's recreate this branch directly off the latest `master`? Seems like we can just directly branch off `master` and cherry-pick ec377809a8f3ea3ffa6b108ce3e150c6bb584b69 instead of going through the hassle of dealing with all the merge conflicts from the recently-merged PRs.

2023-09-18 09:20 UTC, martin-henz commented
@Yongbeom-Kim what's the status of this PR?

2023-09-18 09:21 UTC, martin-henz commented
@Yongbeom-Kim what's the status of this PR?

2023-09-18 10:06 UTC, Cloud7050 commented
@martin-henz to my understanding, @leeyi45 is incorporating these changes into #244. This original PR can probably be closed.

2023-09-18 10:37 UTC, martin-henz commented
> @martin-henz to my understanding, @leeyi45 is incorporating these changes into #244. This original PR can probably be closed.

OK

2023-09-18 10:37 UTC, closed without merging